Refactor course
canvas-gamification/canvas-gamification-ui pull request #183
Opened 2021-06-17 21:36 UTC by aadiraju

## Description
Made course module and moved all components into the module

## Types of changes
What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (only improve the code quality no change in functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] Issue has been created
- [x] Every file touched is linted
- [ ] Every file touched has tests that cover all the funcitonality with green coverage
- [ ] Documentation is updated (if applicable).

## Issue
closes #182 

## Tests
Please describe in detail what tests you added or changed.

## Screenshots (if appropriate):

2021-06-21 00:12 UTC, keyvankhademi requested changes

2021-06-21 00:12 UTC, keyvankhademi commented on src/app/course/course-routing.module.ts
> +        component: CourseEventCreateEditComponent,
Please organize these paths. All the ones start with `:courseId` should be nested.

2021-06-21 00:12 UTC, keyvankhademi commented on src/app/course/course-routing.module.ts
> +        path: 'view/:courseId',
this should be the parent route. We don't need `view` in the url.

2021-06-21 00:12 UTC, keyvankhademi commented on src/app/course/course-routing.module.ts
> +        path: 'register/:courseId',
it's better to have courseid/register.

2021-06-22 15:08 UTC, keyvankhademi approved these changes

2021-06-22 15:09 UTC, keyvankhademi commented
Can you please resolve the conflicts?

2021-06-22 20:46 UTC, aadiraju commented
Conflicts resolved

2021-06-26 03:00 UTC, keyvankhademi approved these changes

2021-06-26 03:00 UTC, merged