Display Medium Instead of Normal
canvas-gamification/canvas-gamification-ui pull request #207
Opened 2021-07-06 23:17 UTC by carson-ricca

## Description
Describe your changes in detail
Update the "NORMAL" in the problem-set to be "MEDIUM"

## Types of changes
What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (only improve the code quality no change in functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [x] Issue has been created
- [x] Every file touched is linted
- [x] Every file touched has tests that cover all the funcitonality with green coverage
- [ ] Documentation is updated (if applicable).

## Issue
Please link the issue here.
- Closes #206 

## Tests
Please describe in detail what tests you added or changed.

## Screenshots (if appropriate):

2021-07-06 23:17 UTC, carson-ricca commented
Did it this way as I remember we talked about this before and we did not want to change it in the backend at that time. Let me know if this is acceptable or if we should change the backend.

2021-07-07 04:53 UTC, keyvankhademi requested changes

2021-07-07 04:53 UTC, keyvankhademi commented on src/app/problems/problem-set/problem-set.component.html
> +        <td mat-cell *matCellDef="let question"> {{question.difficulty === 'NORMAL' ? 'MEDIUM' : question.difficulty || 'No Difficulty'}} </td>
To solve this properly you have to call the difficulty service and find it from there. This will break if difficulties changes.

2021-07-13 01:45 UTC, keyvankhademi approved these changes

2021-07-13 01:46 UTC, merged