Change the display of events from cards to lists
canvas-gamification/canvas-gamification-ui pull request #508
Opened 2022-09-26 10:11 UTC by yuqi88

## Description

- Change the display of events from cards to lists, and styled.
- The order of each section is ordered by the start_date of the events
- Only the grade for coming-soon event displays TBA
- For the teachers, change the wording of the link button
- For the students, the link to the Events page is enabled only when the challenge is available

## Types of changes

What types of changes does your code introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (only improve the code quality no change in functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] Issue has been created
- [ ] Every file touched is linted
- [ ] Every file touched has tests that cover all the funcitonality with green coverage
- [ ] Documentation is updated (if applicable).

## Issue
closes #505 

## Tests

--

## Screenshots (if appropriate):
(1)
![image](https://user-images.githubusercontent.com/60047943/192248599-35e4b07c-4d38-43ef-94c5-c1124b4ad6d9.png)

(2)After clicking the orange Assignment button:
![image](https://user-images.githubusercontent.com/60047943/192248736-93265518-3d59-4fac-88ab-2d4fcfec6f85.png)
Clicking the non-coloured Assignment button displays (1)

(3)After clicking the orange Exam button from (1):
![image](https://user-images.githubusercontent.com/60047943/192249230-15a6355f-9938-4e2e-a889-d400b9fdfb04.png)
Clicking the non-coloured Exam button displays (1)

(4)After clicking both the orange Assignment button & orange Exam button, the page displays (1)

2022-10-06 02:44 UTC, yuqi88 commented
update:
- change the filter to a dropdown
- improve the filter functions
- add the import event card back
- style the edit event button in the list
- add responsiveness

filter: view all assignments & exams
![image](https://user-images.githubusercontent.com/60047943/194201780-673f8c56-be9e-4848-896c-346ad2090eec.png)

filter: view assignments only
![image](https://user-images.githubusercontent.com/60047943/194201889-57e740db-b8ef-4789-8b9d-49bfc0ab6c9b.png)

filter: view exams only
![image](https://user-images.githubusercontent.com/60047943/194201987-6530f855-1a11-415c-8d37-16a3b79a425b.png)

2022-10-06 02:45 UTC, yuqi88 commented
Responsiveness:
![image](https://user-images.githubusercontent.com/60047943/194202387-9a557c78-94f9-4f27-aeaa-cb94457eb9bf.png)
![image](https://user-images.githubusercontent.com/60047943/194202440-39efc177-156b-4bc0-99b9-a2543dc937a5.png)

2022-10-06 03:17 UTC, yuqi88 commented on src/app/course/course-events-snippet/course-events-snippet.component.html
> +                <div class="import-events tui-space_top-8">
Not sure what this does. Is it okay if this stays here?

2022-10-13 20:26 UTC, yuqi88 commented
alignment:
![image](https://user-images.githubusercontent.com/60047943/195703557-b95132b2-b95f-4e41-beec-9d38c37c28cc.png)

![image](https://user-images.githubusercontent.com/60047943/195703661-6bf55d89-42ea-40e8-ab27-11d19e90e488.png)

![image](https://user-images.githubusercontent.com/60047943/195703702-a7caa172-cba0-4ec1-b65f-de32f9f5d9df.png)

2022-10-14 23:28 UTC, keyvankhademi requested changes
Please fix the lint issues. You can also modify eslint to add tabs to the switch case.

2022-10-29 19:04 UTC, keyvankhademi requested changes
Generally looks good.
Can we please make the add event a button instead of that big island?
Also please make sure the tests are passing.
and pull from master and resolve the conflicts.

2022-11-16 01:53 UTC, yuqi88 commented
![image](https://user-images.githubusercontent.com/60047943/202064017-74668d70-1aa5-43ae-88ed-785160d82e46.png)

2022-11-17 01:11 UTC, merged