Display my team in a challenge
canvas-gamification/canvas-gamification-ui pull request #547
Opened 2022-12-01 22:25 UTC by yuqi88

## Description

Describe your changes in detail

## Types of changes

What types of changes does your code introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (only improve the code quality no change in functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] Issue has been created
- [ ] Every file touched is linted
- [ ] Every file touched has tests that cover all the funcitonality with green coverage
- [ ] Documentation is updated (if applicable).

## Issue

Please link the issue here.

## Tests

Please describe in detail what tests you added or changed.

## Screenshots (if appropriate):

2022-12-01 22:29 UTC, yuqi88 commented
![image](https://user-images.githubusercontent.com/60047943/205172667-7b62ee80-c7ce-4df6-8efa-67e72e300f46.png)

2022-12-07 05:54 UTC, keyvankhademi requested changes

2022-12-07 05:54 UTC, keyvankhademi commented on src/app/course/course-question-snippet/course-question-snippet.component.scss
> +    align-items: baseline;
Let's use tailwind classes `flex`, `items-center`, `p-4`, and `rounded` instead of the CSS. we still need the background color in CSS tho.

2022-12-07 05:55 UTC, keyvankhademi commented on src/app/course/course-question-snippet/course-question-snippet.component.scss
> +    margin-left: auto;
To move the button to the right you need to use `flex` with `flex-grow`.

2022-12-28 16:59 UTC, keyvankhademi requested changes

2022-12-28 16:59 UTC, keyvankhademi commented on src/app/_models/team.ts
> +    number_of_member: number;
Why do we have `number of member`? can we not get it from `member_names.length`?

2022-12-28 16:59 UTC, keyvankhademi commented on src/app/course/course-question-snippet/course-question-snippet.component.html
> +                    <ng-template #noComma><p class="tui-text_body-l">{{member_name}}</p></ng-template>
This logic should be in the ts file. `member_names.join(",")`

2022-12-28 21:33 UTC, yuqi88 commented
I made the name of the team and the member names in a separate line.

![image](https://user-images.githubusercontent.com/60047943/209874303-189b582f-bbe7-4c23-8c9a-45d1541afd73.png)

2022-12-29 17:36 UTC, keyvankhademi approved these changes

2022-12-29 17:36 UTC, merged