Minor UI fix
canvas-gamification/canvas-gamification-ui pull request #614
Opened 2023-02-07 19:37 UTC by yuqi88

## Description

Modify team display in the question snippet
Improve button wording: change edit challenge -> save challenge
Add descriptions for each type of challenge
Display the number of pending invites for teams

## Types of changes

What types of changes does your code introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Refactor (only improve the code quality no change in functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] Issue has been created
- [ ] Every file touched is linted
- [ ] Every file touched has tests that cover all the funcitonality with green coverage
- [ ] Documentation is updated (if applicable).

## Issue

Please link the issue here.

closes #610 #611 #612 #613 

Please describe in detail what tests you added or changed.

## Screenshots (if appropriate):

2023-02-08 16:31 UTC, yuqi88 commented
![image](https://user-images.githubusercontent.com/60047943/217591870-b76c2674-417b-47cb-bce2-17a6fac215e2.png)

2023-02-08 16:33 UTC, yuqi88 commented
![image](https://user-images.githubusercontent.com/60047943/217592246-2cb9ce38-52bc-4127-877c-832665ea5083.png)

2023-02-08 21:53 UTC, keyvankhademi requested changes

2023-02-08 21:53 UTC, keyvankhademi commented on src/app/course/course-question-snippet/course-question-snippet.component.html
> +                    }"
```suggestion
            [class.mb-10]="event.type !== 'CHALLENGE'"
```

2023-02-14 17:31 UTC, keyvankhademi approved these changes

2023-02-14 18:43 UTC, merged