Navigation in challenge questions
canvas-gamification/canvas-gamification-ui pull request #660
Opened 2023-03-16 04:00 UTC by yuqi88

## Description

Describe your changes in detail

## Types of changes

What types of changes does your code introduce?

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Refactor (only improve the code quality no change in functionality)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] Issue has been created
- [ ] Every file touched is linted
- [ ] Every file touched has tests that cover all the funcitonality with green coverage
- [ ] Documentation is updated (if applicable).

## Issue

closes #659 

## Tests

Please describe in detail what tests you added or changed.

## Screenshots (if appropriate):

2023-03-21 22:24 UTC, keyvankhademi commented on src/app/course/event/event-question-view/event-question-view.component.scss
> +.eventQuestionView {
use tailwind

2023-03-24 00:37 UTC, keyvankhademi commented on src/app/course/event/event-question-view/event-question-view.component.scss
> +@import "mixins";
we dont need this anymore

2023-03-31 01:56 UTC, yuqi88 commented
<img width="440" alt="image" src="https://user-images.githubusercontent.com/60047943/229003325-0479ba5b-69fd-486d-992e-edbe5d4e62a7.png">

2023-04-01 20:09 UTC, keyvankhademi requested changes

2023-04-01 20:09 UTC, keyvankhademi commented on src/app/course/course-routing.module.ts
> +        path: ':courseId/challenge/:eventId/problem/:id',
what about assignments and exams? We need to have the nav for both of them.

2023-04-03 20:34 UTC, keyvankhademi requested changes

2023-04-03 20:34 UTC, keyvankhademi commented on src/app/course/event/event-question-view/event-question-view.component.html
> +                Back to Challenge
It can either be an assignment or a challenge here, right?

2023-04-03 20:34 UTC, keyvankhademi commented on src/app/course/event/event-question-view/event-question-view.component.ts
> +                this.uqjs = orderUQJs(this.uqjs)
```suggestion
                this.uqjs = orderUQJs(result.results)
```

2023-04-03 21:08 UTC, keyvankhademi approved these changes

2023-04-03 21:10 UTC, merged